Repository LucioGuerra/ProyectoGym, pull requests merged in 2024-09, with the labels that each got.

#6 Framework/backend/scrum2 crear aquitectura usuario
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/controller/UserController.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/entity/user/User.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/repository/UserRepository.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/service/UserService.java
  BackEnd/criminal/target/classes/application.properties
  BackEnd/criminal/target/classes/com/desarrollo/criminal/CriminalApplication.class
Labels: framework

#7 Framework: Crear Actividad | SCRUM-89
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/CriminalApplication.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/controller/ActivityController.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/dto/request/ActivityDTO.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/entity/Activity.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/entity/tracking/Tracking.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/service/ActivityService.java
  BackEnd/criminal/target/classes/application.properties
  BackEnd/criminal/target/test-classes/com/desarrollo/criminal/CriminalApplicationTests.class
Labels: framework

#9 Feature: Implementacion de auth0 en bakend y en frontend | SCRUM-66
  BackEnd/criminal/pom.xml
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/configuration/SecurityConfig.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/controller/ActivityController.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/controller/ExerciseController.java
  BackEnd/criminal/src/main/resources/application.properties
  FrontEnd/src/app/src/components/home-page/home-page.component.ts
  FrontEnd/src/app/src/components/login/login.component.ts
  FrontEnd/src/app/src/components/services/services/auth.service.ts
  FrontEnd/src/app/src/components/singup/singup.component.ts
  FrontEnd/yarn.lock
Labels: feature

#8 Feature: crear endpoint y creacion de turnos | SCRUM 20
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/controller/AppointmentController.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/controller/UserController.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/dto/request/AppointmentDTO.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/entity/Appointment.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/repository/AppointmentRepository.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/service/ActivityService.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/service/AppointmentService.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/service/UserService.java
Labels: feature

#11 Feature: Vista Modificar Usuario | SCRUM-77
  FrontEnd/package.json
  FrontEnd/src/app/app.routes.ts
  FrontEnd/src/app/src/components/models/user.models.ts
  FrontEnd/src/app/src/components/user-edit/user-edit.component.html
  FrontEnd/src/app/src/components/user-edit/user-edit.component.scss
  FrontEnd/src/app/src/components/user-edit/user-edit.component.spec.ts
  FrontEnd/src/app/src/components/user-edit/user-edit.component.ts
  FrontEnd/yarn.lock
Labels: design
