Repository LucioGuerra/ProyectoGym, pull requests merged in 2024-10, with the labels that each got.

#12 Feature: Integrar auth0 | SCRUM-99
  FrontEnd/package.json
  FrontEnd/src/app/src/components/drawer/drawer.component.ts
  FrontEnd/src/app/src/components/home-page/home-page.component.ts
  FrontEnd/src/app/src/components/services/services/auth.service.ts
  FrontEnd/src/app/src/components/user-profile/user-profile.component.ts
  FrontEnd/src/app/src/layout/shif-admin-screen/shif-admin-screen.component.ts
  FrontEnd/yarn.lock
Labels: feature

#16 Feature: terminar funcionalidades de appointment | SCRUM94
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/configuration/ModelMapperConfig.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/controller/ActivityController.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/controller/AppointmentController.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/controller/UserController.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/dto/request/AppointmentDTO.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/dto/request/UpdatePATCHAppointmentDTO.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/dto/response/AppointmentListResponseDTO.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/dto/response/AppointmentResponseDTO.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/dto/response/AppointmentUserDTO.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/entity/Appointment.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/repository/ActivityRepository.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/repository/AppointmentRepository.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/repository/UserRepository.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/service/ActivityService.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/service/AppointmentService.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/service/UserService.java
Labels: feature

#13 Feature: crear create_user | SCRUM-101
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/controller/UserController.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/dto/reponse/UserResponseDTO.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/dto/request/UserRequestDTO.java
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/service/UserService.java
  BackEnd/criminal/target/classes/com/desarrollo/criminal/CriminalApplication.class
  BackEnd/criminal/target/test-classes/com/desarrollo/criminal/CriminalApplicationTests.class
  FrontEnd/package-lock.json
Labels: framework

#20 Design: Diseñar y codificar vista de lista de usuarios (solo para admins) | SCRUM-108
  BackEnd/criminal/src/main/Java/com/desarrollo/criminal/configuration/SecurityConfig.java
  FrontEnd/src/app/app.config.ts
  FrontEnd/src/app/app.routes.ts
  FrontEnd/src/app/src/components/drawer/drawer.component.ts
  FrontEnd/src/app/src/components/models/index.ts
  FrontEnd/src/app/src/components/models/user.models.ts
  FrontEnd/src/app/src/components/models/userModel.models.ts
  FrontEnd/src/app/src/components/services/services/api.service.ts
  FrontEnd/src/app/src/components/services/services/auth.service.ts
  FrontEnd/src/app/src/components/services/services/user.service.spec.ts
  FrontEnd/src/app/src/components/services/services/user.service.ts
  FrontEnd/src/app/src/components/user-edit/user-edit.component.scss
  FrontEnd/src/app/src/components/user-edit/user-edit.component.ts
  FrontEnd/src/app/src/components/users-list/users-list.component.html
  FrontEnd/src/app/src/components/users-list/users-list.component.scss
  FrontEnd/src/app/src/components/users-list/users-list.component.spec.ts
  FrontEnd/src/app/src/components/users-list/users-list.component.ts
Labels: design
